export interface Option {
  label: string;
  value: string;
}

export interface Field {
  id: string;
  label: string;
  options?: Option[];
  type: 'dropdown' | 'text';
}

export const FIELDS: Field[] = [
  {
    id: 'parentCampaign',
    label: 'Parent Campaign',
    type: 'dropdown',
    options: [
      { label: 'Prospecting', value: 'Prsp' },
      { label: 'Engaged', value: 'Eng' },
      { label: 'Evaluating', value: 'Evl' },
      { label: 'Buying', value: 'Buy' },
      { label: 'Enterprise', value: 'ENTER' },
      { label: 'Acceleration', value: 'ACCL' },
      { label: 'Mama', value: 'MMA' },
      { label: 'Hiring', value: 'HR' },
      { label: 'Product release', value: 'PRL' },
      { label: 'Brand', value: 'BRD' },
      { label: 'Search', value: 'Search' },
      { label: 'Upsell', value: 'USL' },
      { label: 'General', value: 'Gnrl' },
    ],
  },
  {
    id: 'mediaSource',
    label: 'Media Source',
    type: 'dropdown',
    options: [
      { label: 'YouTube', value: 'YTB' },
      { label: 'Yandex Network', value: 'YNW' },
      { label: 'Yandex Direct', value: 'YDX' },
      { label: 'Xing', value: 'XNG' },
      { label: 'X', value: 'X' },
      { label: 'Taboola', value: 'TB' },
      { label: 'Reddit', value: 'RDT' },
      { label: 'Quora', value: 'QU' },
      { label: 'Outbrain', value: 'OB' },
      { label: 'Naver', value: 'NVR' },
      { label: 'LinkedIn', value: 'LI' },
      { label: 'Google', value: 'GG' },
      { label: 'Facebook', value: 'FB' },
      { label: 'eMarketer', value: 'eM' },
      { label: 'Bing', value: 'BG' },
      { label: 'Baidu', value: 'BD' },
      { label: 'Capterra', value: 'CAP' },
      { label: 'Tiktok', value: 'TK' },
      { label: 'Wechat', value: 'WCT' },
      { label: 'KakaoTalk', value: 'KKT' },
      { label: 'Snapchat', value: 'SNC' },
      { label: 'Influencer', value: 'Influencer' },
      { label: 'CTV', value: 'CTV' },
      { label: 'Partner', value: 'Partner' },
      { label: 'Spotify', value: 'Sptfy' },
      { label: 'Apple', value: 'APPL' },
      { label: 'Marketo', value: 'MKTO' },
      { label: 'New channel', value: 'NEW' },
    ],
  },
  {
    id: 'region',
    label: 'CBU / Region',
    type: 'dropdown',
    options: [
      { label: 'Africa', value: 'EMEA-AFR' },
      { label: 'APAC', value: 'APAC-ALL' },
      { label: 'AU / NZ', value: 'APAC-ANZ' },
      { label: 'Brazil', value: 'LATAM-BRA' },
      { label: 'CA', value: 'NA-CA' },
      { label: 'Central Europe', value: 'EMEA-CTR' },
      { label: 'China', value: 'GCR' },
      { label: 'Eastern Europe', value: 'EMEA-EST' },
      { label: 'EMEA', value: 'EMEA-ALL' },
      { label: 'EU Other / IL', value: 'EMEA-EUO' },
      { label: 'FR', value: 'EMEA-FR' },
      { label: 'Germany', value: 'EMEA-DE' },
      { label: 'Global', value: 'HQ' },
      { label: 'India', value: 'APAC-IND' },
      { label: 'Israel', value: 'EMEA-IL' },
      { label: 'Italy', value: 'EMEA-IT' },
      { label: 'Japan', value: 'APAC-JPN' },
      { label: 'LATAM', value: 'LATAM-ALL' },
      { label: 'Middle East', value: 'EMEA-ME' },
      { label: 'Nordics', value: 'EMEA-NRD' },
      { label: 'North America', value: 'NA' },
      { label: 'ROA', value: 'APAC-ROA' },
      { label: 'Russia', value: 'EMEA-RU' },
      { label: 'Russia / CIS', value: 'EMEA-CIS' },
      { label: 'SANI', value: 'EMEA-SANI' },
      { label: 'SEA', value: 'APAC-SEA' },
      { label: 'Singapore', value: 'APAC-SG' },
      { label: 'South Korea', value: 'APAC-KOR' },
      { label: 'Spain', value: 'EMEA-SP' },
      { label: 'Spanish LATAM', value: 'LATAM-SP' },
      { label: 'TR', value: 'EMEA-TR' },
      { label: 'UK', value: 'EMEA-UK' },
      { label: 'US', value: 'NA-US' },
      { label: 'Vietnam', value: 'APAC-VN' },
      { label: 'WE&MENAT', value: 'EMEA-WEMET' },
      { label: 'Western Europe', value: 'EMEA-WST' },
    ],
  },
  {
    id: 'targetingType',
    label: 'Targeting Type',
    type: 'dropdown',
    options: [
      { label: 'New Audience', value: 'New' },
      { label: 'Brand Keywords', value: 'KW-BRND' },
      { label: 'Competitor Keywords', value: 'KW-CMP' },
      { label: 'Generic Keywords', value: 'KW-GNRC' },
      { label: 'Lookalike', value: 'LAL' },
      { label: 'SAM', value: 'SAM' },
      { label: 'TAM', value: 'TAM' },
      { label: 'List', value: 'LST' },
      { label: 'Re-Marketing', value: 'REM-ALL' },
      { label: 'Re-Marketing High Intent', value: 'REM-HT' },
      { label: 'Re-Marketing Low Intent', value: 'REM-LT' },
      { label: 'External Source', value: 'EXTNL' },
      { label: 'Mixed', value: 'TMix' },
    ],
  },
  {
    id: 'audienceSegment',
    label: 'Audience Segment',
    type: 'dropdown',
    options: [
      { label: 'Longtail', value: 'Lngtl' },
      { label: 'Growth', value: 'Grt' },
      { label: 'Enterprise', value: 'Entrp' },
      { label: 'Longtail and Growth', value: 'Lngtl-Grt' },
      { label: 'Growth and Enterprise', value: 'Grt-Entrp' },
      { label: 'All tiers', value: 'Any' },
    ],
  },
  {
    id: 'audienceMotion',
    label: 'Audience Motion',
    type: 'dropdown',
    options: [
      { label: 'Rip & Riplace', value: 'RnR' },
      { label: 'Greenfield', value: 'Grfd' },
      { label: 'Customer', value: 'CSTMR' },
      { label: 'Churned', value: 'Chrn' },
      { label: 'Mixed', value: 'Mixed' },
    ],
  },
  {
    id: 'audienceVertical',
    label: 'Audience Vertical',
    type: 'dropdown',
    options: [
      { label: 'eCommerce / Retail', value: 'Ecom' },
      { label: 'Finance', value: 'Finc' },
      { label: 'Games', value: 'Gmng' },
      { label: 'Miscellaneous', value: 'Mscl' },
      { label: 'Subscription - Based', value: 'Subs' },
      { label: 'Food and Drink', value: 'Fnd' },
      { label: 'Health and fitness', value: 'Hnf' },
      { label: 'Travel', value: 'Trvl' },
      { label: 'Entertainment', value: 'Etrmnt' },
      { label: 'Mixed', value: 'Vmix' },
    ],
  },
  {
    id: 'platformObjective',
    label: 'Platform Objective',
    type: 'dropdown',
    options: [
      { label: 'Website conversion', value: 'wbcvr' },
      { label: 'Video views', value: 'vview' },
      { label: 'Traffic', value: 'trfic' },
      { label: 'Reach', value: 'reach' },
      { label: 'Clicks', value: 'click' },
      { label: 'Lead Gen form', value: 'lgf' },
      { label: 'Job applications', value: 'jobap' },
      { label: 'Frequency', value: 'frqcy' },
      { label: 'Followers', value: 'flwr' },
      { label: 'Engagement', value: 'engag' },
    ],
  },
  {
    id: 'offeringType',
    label: 'Offering Type',
    type: 'dropdown',
    options: [
      { label: 'Demo Requests', value: 'Demo' },
      { label: 'SignUp', value: 'Sgnup' },
      { label: 'Demo and Signup', value: 'DEM-SGP' },
      { label: 'Gated Content', value: 'Gated' },
      { label: 'Ungated content', value: 'Ungtd' },
      { label: 'Interactive demos', value: 'Intr-dem' },
      { label: 'Demo on Demand', value: 'DOD' },
      { label: 'On platform video', value: 'Plt-vid' },
      { label: 'On platform asset', value: 'Plt-otr' },
      { label: 'Offline event', value: 'Event' },
      { label: 'Webinar', value: 'Webnr' },
      { label: 'Quizz', value: 'Quz' },
      { label: 'HR Recruiting', value: 'HRrec' },
      { label: 'Expert call', value: 'Exp-call' },
      { label: 'Other', value: 'OTR' },
    ],
  },
  {
    id: 'language',
    label: 'Language',
    type: 'dropdown',
    options: [
      { label: 'Vietnamese', value: 'VN' },
      { label: 'Ukrainian', value: 'UA' },
      { label: 'Spanish', value: 'SP' },
      { label: 'Russian', value: 'RU' },
      { label: 'Portuguese', value: 'PT' },
      { label: 'Korean', value: 'KR' },
      { label: 'Japanese', value: 'JP' },
      { label: 'Bahasa', value: 'ID' },
      { label: 'French', value: 'FR' },
      { label: 'English', value: 'EN' },
      { label: 'German', value: 'DE' },
      { label: 'Chinese', value: 'CN' },
    ],
  },
  {
    id: 'freeText',
    label: 'Free Text',
    type: 'text',
  },
  {
    id: 'startDate',
    label: 'Start Date',
    type: 'text',
  },
];
